services:
    mongo: # mongodb
        container_name: mongo_ekhidata
        image: mongo:4.0
        restart: unless-stopped
        env_file:
            - ./server/.env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
        ports:
            - ${MONGO_PORT}:27017
        volumes:
            - ./server/database/mongo-init:/docker-entrypoint-initdb.d:ro
            - /data/db
        networks:
            - fullstack_network
    backend:
        build: ./server
        container_name: ${APP_HOST}
        restart: unless-stopped
        env_file:
            - ./server/.env
        ports:
            - ${APP_PORT}:3000
        depends_on:
            - mongo
        volumes:
            - ./server:/app
            - /app/node_modules
        networks:
            - fullstack_network
    frontend:
        build: ./client
        container_name: frontend
        restart: unless-stopped
        ports:
            - 5173:5173
        volumes:
            - ./client:/app
            - /app/node_modules

volumes:
    mongodb_data:
networks:
    fullstack_network:
    data_netrwork:
    api_network:
