const mockData = [
    {
        "fecha": "2025-01-09",
        "año": "2025",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "15,00",
        "concepto": "Ekhilur kuota urtebete",
        "usuario_asociado": "Ekhilur S.Coop.",
        "saldo": "15,00",
        "cuenta": "Ekhi Hernani"
    },
    {
        "fecha": "2025-01-09",
        "año": "2025",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "1,00",
        "concepto": "Froga",
        "usuario_asociado": "Alejandro Lopez Morgado",
        "saldo": "16,00",
        "cuenta": "Ekhi"
    },
    {
        "fecha": "2025-01-09",
        "año": "2025",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "1,00",
        "concepto": "froga",
        "usuario_asociado": "Alejandro Lopez Morgado",
        "saldo": "15,00",
        "cuenta": "Ekhi"
    },
    {
        "fecha": "2025-01-13",
        "año": "2025",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "1,00",
        "concepto": "froga",
        "usuario_asociado": "Herrilur Kontsumo Elkartea",
        "saldo": "14,00",
        "cuenta": "Ekhi Hernani"
    },
    {
        "fecha": "2025-01-13",
        "año": "2025",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "1,00",
        "concepto": "",
        "usuario_asociado": "Herrilur Kontsumo Elkartea",
        "saldo": "15,00",
        "cuenta": "Ekhi"
    },
    {
        "fecha": "2025-01-17",
        "año": "2025",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Recarga por tarjeta",
        "cantidad": "50,00",
        "concepto": "",
        "usuario_asociado": "",
        "saldo": "65,00",
        "cuenta": "Euro"
    },
    {
        "fecha": "2025-01-17",
        "año": "2025",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "32,55",
        "concepto": "aliprox",
        "usuario_asociado": "Aliprox",
        "saldo": "32,45",
        "cuenta": "Euro"
    },
    {
        "fecha": "2025-01-19",
        "año": "2025",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "1,40",
        "concepto": "",
        "usuario_asociado": "Tripontzi Jatetxea",
        "saldo": "31,05",
        "cuenta": "Euro"
    },
    {
        "fecha": "2025-01-20",
        "año": "2025",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Recarga por tarjeta",
        "cantidad": "100,00",
        "concepto": "",
        "usuario_asociado": "",
        "saldo": "131,05",
        "cuenta": "Euro"
    },
    {
        "fecha": "2025-01-23",
        "año": "2025",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "7,30",
        "concepto": "",
        "usuario_asociado": "On Bit Informatika",
        "saldo": "123,75",
        "cuenta": "Ekhi Hernani"
    },
    {
        "fecha": "2025-01-23",
        "año": "2025",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "1,00",
        "concepto": "froga",
        "usuario_asociado": "Herrilur Kontsumo Elkartea",
        "saldo": "122,75",
        "cuenta": "Ekhi"
    },
    {
        "fecha": "2025-01-23",
        "año": "2025",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "1,00",
        "concepto": "Bueltan",
        "usuario_asociado": "Herrilur Kontsumo Elkartea",
        "saldo": "123,75",
        "cuenta": "Ekhi Hernani"
    },
    {
        "fecha": "2025-01-24",
        "año": "2025",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "1,00",
        "concepto": "froga",
        "usuario_asociado": "Galarreta Pilotalekua",
        "saldo": "122,75",
        "cuenta": "Euro"
    },
    {
        "fecha": "2025-01-24",
        "año": "2025",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "1,00",
        "concepto": "froga buelta",
        "usuario_asociado": "Galarreta Pilotalekua",
        "saldo": "123,75",
        "cuenta": "Ekhi"
    },
    {
        "fecha": "2025-01-24",
        "año": "2025",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "1,00",
        "concepto": "droga",
        "usuario_asociado": "Ereñozuko denda (Coviran)",
        "saldo": "122,75",
        "cuenta": "Ekhi"
    },
    {
        "fecha": "2025-01-24",
        "año": "2025",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "1,00",
        "concepto": "Devolucion",
        "usuario_asociado": "Ereñozuko denda (Coviran)",
        "saldo": "123,75",
        "cuenta": "Ekhi"
    },
    {
        "fecha": "2025-01-25",
        "año": "2025",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "15,94",
        "concepto": "",
        "usuario_asociado": "Artola Harategia",
        "saldo": "107,81",
        "cuenta": "Euro"
    },
    {
        "fecha": "2025-01-27",
        "año": "2025",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "1,00",
        "concepto": "froga",
        "usuario_asociado": "Gaindituz Fisioterapia",
        "saldo": "106,81",
        "cuenta": "Euro"
    },
    {
        "fecha": "2025-01-27",
        "año": "2025",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "1,00",
        "concepto": "",
        "usuario_asociado": "Aliprox",
        "saldo": "107,81",
        "cuenta": "Ekhi"
    },
    {
        "fecha": "2024-01-24",
        "año": "2024",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "0,56",
        "concepto": "",
        "usuario_asociado": "Oa Gozotegia",
        "saldo": "107,81",
        "cuenta": "Ekhi"
    },
    {
        "fecha": "2024-01-24",
        "año": "2024",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "0,56",
        "concepto": "",
        "usuario_asociado": "Oa Gozotegia",
        "saldo": "107,81",
        "cuenta": "Ekhi"
    },
    {
        "fecha": "2024-01-12",
        "año": "2024",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "1,00",
        "concepto": "",
        "usuario_asociado": "Gaindituz Fisioterapia",
        "saldo": "107,81",
        "cuenta": "Ekhi"
    },
    {
        "fecha": "2024-01-21",
        "año": "2024",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "1,00",
        "concepto": "",
        "usuario_asociado": "Gaindituz Fisioterapia",
        "saldo": "107,81",
        "cuenta": "Ekhi"
    },
    {
        "fecha": "2024-01-29",
        "año": "2024",
        "mes": "01",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "1,00",
        "concepto": "",
        "usuario_asociado": "Gaindituz Fisioterapia",
        "saldo": "107,81",
        "cuenta": "Ekhi"
    },
    {
        "fecha": "2024-12-05",
        "año": "2024",
        "mes": "12",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "1,00",
        "concepto": "",
        "usuario_asociado": "Gaindituz Fisioterapia",
        "saldo": "107,81",
        "cuenta": "Ekhi"
    },
    {
        "fecha": "2024-12-08",
        "año": "2024",
        "mes": "12",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "1,00",
        "concepto": "",
        "usuario_asociado": "Gaindituz Fisioterapia",
        "saldo": "107,81",
        "cuenta": "Ekhi"
    },
    {
        "fecha": "2024-12-24",
        "año": "2024",
        "mes": "12",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "0,56",
        "concepto": "",
        "usuario_asociado": "Oa Gozotegia",
        "saldo": "107,81",
        "cuenta": "Ekhi"
    },
    {
        "fecha": "2024-12-13",
        "año": "2024",
        "mes": "12",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "1,00",
        "concepto": "froga",
        "usuario_asociado": "Herrilur Kontsumo Elkartea",
        "saldo": "14,00",
        "cuenta": "Ekhi Hernani"
    },
    {
        "fecha": "2024-12-13",
        "año": "2024",
        "mes": "12",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "1,00",
        "concepto": "",
        "usuario_asociado": "Herrilur Kontsumo Elkartea",
        "saldo": "15,00",
        "cuenta": "Ekhi"
    },
    {
        "fecha": "2024-12-23",
        "año": "2024",
        "mes": "12",
        "hora": "11:11",
        "movimiento": "Pago a usuario",
        "cantidad": "7,30",
        "concepto": "",
        "usuario_asociado": "On Bit Informatika",
        "saldo": "123,75",
        "cuenta": "Ekhi Hernani"
    },
];

export default mockData;