const mockData = [
    {
        "fecha":"2024-12-20",
        "año":"2024",
        "mes":"12", 
        "hora":"10:23",
        "movimiento":"Transferencia enviada",
        "cantidad": -95.17,
        "concepto":"Pago de servicio",
        "usuario_asociado": "Tienda EcoVida",
        "saldo":148.89,
        "cuenta":"Cuenta 3",
        "categoria":"Moda y complementos"
    },
    {
        "fecha":"2024-12-20",
        "año":"2024",
        "mes":"12", 
        "hora":"08:22",
        "movimiento":"Ingreso recibido",
        "cantidad": 8.57,
        "concepto":"Compra en tienda",
        "usuario_asociado": "Covirán",
        "saldo":314.66,
        "cuenta":"Cuenta 3",
        "categoria":"Industria y construcción"
    },
    {
        "fecha":"2024-12-01",
        "año":"2024",
        "mes":"12", 
        "hora":"01:20",
        "movimiento":"Pago a usuario",
        "cantidad": 81.0,
        "concepto":"Donación",
        "usuario_asociado": "Bar El Rincón",
        "saldo":366.02,
        "cuenta":"Cuenta 2",
        "categoria":"Arte y cultura"
    },
    {
        "fecha":"2024-12-01",
        "año":"2024",
        "mes":"12", 
        "hora":"08:29",
        "movimiento":"Ingreso recibido",
        "cantidad": 80.66,
        "concepto":"Cuota mensual",
        "usuario_asociado": "Bodega El Vino Bueno",
        "saldo":66.0,
        "cuenta":"Cuenta 1",
        "categoria":"Servicios y comercio general"
    },
    {
        "fecha":"2024-12-28",
        "año":"2024",
        "mes":"12", 
        "hora":"09:09",
        "movimiento":"Pago a usuario",
        "cantidad": 68.24,
        "concepto":"Pago de servicio",
        "usuario_asociado": "Pescadería El Mar",
        "saldo":309.82,
        "cuenta":"Cuenta 1",
        "categoria":"Hostelería"
    },
    {
        "fecha":"2024-12-28",
        "año":"2024",
        "mes":"12", 
        "hora":"03:49",
        "movimiento":"Pago a usuario",
        "cantidad": 71.33,
        "concepto":"Pago de servicio",
        "usuario_asociado": "Covirán",
        "saldo":400.64,
        "cuenta":"Cuenta 2",
        "categoria":"Asociaciones y cooperativas"
    },
    {
        "fecha":"2024-12-14",
        "año":"2024",
        "mes":"12", 
        "hora":"15:09",
        "movimiento":"Transferencia enviada",
        "cantidad": -17.64,
        "concepto":"Compra en tienda",
        "usuario_asociado": "Pescadería El Mar",
        "saldo":273.3,
        "cuenta":"Cuenta 2",
        "categoria":"Industria y construcción"
    },
    {
        "fecha":"2024-12-05",
        "año":"2024",
        "mes":"12", 
        "hora":"01:53",
        "movimiento":"Transferencia enviada",
        "cantidad": -24.49,
        "concepto":"Donación",
        "usuario_asociado": "Tienda EcoVida",
        "saldo":478.73,
        "cuenta":"Cuenta 2",
        "categoria":"Moda y complementos"
    },
    {
        "fecha":"2024-12-05",
        "año":"2024",
        "mes":"12", 
        "hora":"03:03",
        "movimiento":"Transferencia enviada",
        "cantidad": -34.35,
        "concepto":"Donación",
        "usuario_asociado": "Frutería La Huerta",
        "saldo":224.07,
        "cuenta":"Cuenta 3",
        "categoria":"Moda y complementos"
    },
    {
        "fecha":"2024-12-05",
        "año":"2024",
        "mes":"12", 
        "hora":"01:04",
        "movimiento":"Pago a usuario",
        "cantidad": 67.86,
        "concepto":"Donación",
        "usuario_asociado": "Bodega El Vino Bueno",
        "saldo":41.0,
        "cuenta":"Cuenta 1",
        "categoria":"Salud y estética"
    },
    {
        "fecha":"2024-12-30",
        "año":"2024",
        "mes":"12", 
        "hora":"04:14",
        "movimiento":"Pago a usuario",
        "cantidad": 13.81,
        "concepto":"Compra en tienda",
        "usuario_asociado": "Supermercado Díaz",
        "saldo":446.43,
        "cuenta":"Cuenta 2",
        "categoria":"Alimentación"
    },
    {
        "fecha":"2024-01-30",
        "año":"2024",
        "mes":"01", 
        "hora":"22:35",
        "movimiento":"Transferencia enviada",
        "cantidad": -76.85,
        "concepto":"Pago de servicio",
        "usuario_asociado": "Carnicería Jose Luis",
        "saldo":307.54,
        "cuenta":"Ekhi Hernani",
        "categoria":"Arte y cultura"
    },
    {
        "fecha":"2024-01-30",
        "año":"2024",
        "mes":"01", 
        "hora":"18:21",
        "movimiento":"Ingreso recibido",
        "cantidad": 57.03,
        "concepto":"Donación",
        "usuario_asociado": "Tripontzi Jatetxea",
        "saldo":64.41,
        "cuenta":"Cuenta 3",
        "categoria":"Asociaciones y cooperativas"
    },
    {
        "fecha":"2024-01-04",
        "año":"2024",
        "mes":"01", 
        "hora":"11:06",
        "movimiento":"Ingreso recibido",
        "cantidad": 44.39,
        "concepto":"Pago de servicio",
        "usuario_asociado": "Bar El Rincón",
        "saldo":461.7,
        "cuenta":"Ekhi Hernani",
        "categoria":"Alimentación"
    },
    {
        "fecha":"2024-01-04",
        "año":"2024",
        "mes":"01", 
        "hora":"12:34",
        "movimiento":"Transferencia enviada",
        "cantidad": -88.61,
        "concepto":"Pago de servicio",
        "usuario_asociado": "Tripontzi Jatetxea",
        "saldo":269.12,
        "cuenta":"Cuenta 3",
        "categoria":"Deporte y ocio"
    },
    {
        "fecha":"2025-01-04",
        "año":"2025",
        "mes":"01", 
        "hora":"19:40",
        "movimiento":"Ingreso recibido",
        "cantidad": 86.95,
        "concepto":"Compra en tienda",
        "usuario_asociado": "Panadería OA",
        "saldo":350.12,
        "cuenta":"Cuenta 2",
        "categoria":"Hostelería"
    },
    {
        "fecha":"2025-01-04",
        "año":"2025",
        "mes":"01", 
        "hora":"06:42",
        "movimiento":"Pago a usuario",
        "cantidad": 52.86,
        "concepto":"Donación",
        "usuario_asociado": "Frutería La Huerta",
        "saldo":386.93,
        "cuenta":"Cuenta 1",
        "categoria":"Alimentación"
    },
    {
        "fecha":"2025-01-07",
        "año":"2025",
        "mes":"01", 
        "hora":"18:29",
        "movimiento":"Ingreso recibido",
        "cantidad": 8.64,
        "concepto":"Pago de servicio",
        "usuario_asociado": "Bar El Rincón",
        "saldo":51.66,
        "cuenta":"Ekhi Hernani",
        "categoria":"Alimentación"
    },
    {
        "fecha":"2025-01-09",
        "año":"2025",
        "mes":"01", 
        "hora":"08:46",
        "movimiento":"Ingreso recibido",
        "cantidad": 5.86,
        "concepto":"Donación",
        "usuario_asociado": "Bar El Rincón",
        "saldo":174.16,
        "cuenta":"Cuenta 1",
        "categoria":"Salud y estética"
    },
    {
        "fecha":"2025-01-09",
        "año":"2025",
        "mes":"01", 
        "hora":"19:41",
        "movimiento":"Pago a usuario",
        "cantidad": 65.14,
        "concepto":"Compra en tienda",
        "usuario_asociado": "Tienda EcoVida",
        "saldo":384.67,
        "cuenta":"Cuenta 2",
        "categoria":"Salud y estética"
    },
    {
        "fecha":"2025-01-07",
        "año":"2025",
        "mes":"01",
        "hora":"21:22",
        "movimiento":"Pago a usuario",
        "cantidad": 45.7,
        "concepto":"Compra en tienda",
        "usuario_asociado": "Frutería La Huerta",
        "saldo":235.94,
        "cuenta":"Cuenta 1",
        "categoria":"Hostelería"
    },
    {
        "fecha":"2025-01-07",
        "año":"2025",
        "mes":"01",
        "hora":"14:52",
        "movimiento":"Pago a usuario",
        "cantidad": 23.94,
        "concepto":"Compra en tienda",
        "usuario_asociado": "Panadería OA",
        "saldo":101.99,
        "cuenta":"Ekhi Hernani",
        "categoria":"Salud y estética"
    },
    {
        "fecha":"2025-01-07",
        "año":"2025",
        "mes":"01",
        "hora":"07:19",
        "movimiento":"Transferencia enviada",
        "cantidad": -26.03,
        "concepto":"Cuota mensual",
        "usuario_asociado": "Carnicería Jose Luis",
        "saldo":72.42,
        "cuenta":"Cuenta 3",
        "categoria":"Asociaciones y cooperativas"
    },
    {
        "fecha":"2025-01-15",
        "año":"2025",
        "mes":"01",
        "hora":"17:52",
        "movimiento":"Pago a usuario",
        "cantidad": 94.68,
        "concepto":"Compra en tienda",
        "usuario_asociado": "Panadería OA",
        "saldo":198.67,
        "cuenta":"Cuenta 1",
        "categoria":"Asociaciones y cooperativas"
    },
    {
        "fecha":"2025-01-15",
        "año":"2025",
        "mes":"01",
        "hora":"04:11",
        "movimiento":"Ingreso recibido",
        "cantidad": 90.63,
        "concepto":"Cuota mensual",
        "usuario_asociado": "Panadería OA",
        "saldo":199.1,
        "cuenta":"Ekhi Hernani",
        "categoria":"Moda y complementos"
    },
    {
        "fecha":"2025-01-01",
        "año":"2025",
        "mes":"01",
        "hora":"11:00",
        "movimiento":"Ingreso recibido",
        "cantidad": 96.11,
        "concepto":"Compra en tienda",
        "usuario_asociado": "Supermercado Díaz",
        "saldo":407.22,
        "cuenta":"Ekhi Hernani",
        "categoria":"Deporte y ocio"
    },
    {
        "fecha":"2025-01-01",
        "año":"2025",
        "mes":"01",
        "hora":"21:44",
        "movimiento":"Pago a usuario",
        "cantidad": 19.62,
        "concepto":"Pago de servicio",
        "usuario_asociado": "Carnicería Jose Luis",
        "saldo":229.67,
        "cuenta":"Cuenta 2",
        "categoria":"Moda y complementos"
    },
    {
        "fecha":"2025-01-01",
        "año":"2025",
        "mes":"01",
        "hora":"05:15",
        "movimiento":"Ingreso recibido",
        "cantidad": 82.06,
        "concepto":"Donación",
        "usuario_asociado": "Bodega El Vino Bueno",
        "saldo":487.31,
        "cuenta":"Cuenta 3",
        "categoria":"Alimentación"
    },
    {
        "fecha":"2025-01-12",
        "año":"2025",
        "mes":"01",
        "hora":"07:39",
        "movimiento":"Pago a usuario",
        "cantidad": 31.24,
        "concepto":"Compra en tienda",
        "usuario_asociado": "Tripontzi Jatetxea",
        "saldo":32.43,
        "cuenta":"Cuenta 3",
        "categoria":"Asociaciones y cooperativas"
    },
    {
        "fecha":"2025-01-12",
        "año":"2025",
        "mes":"01",
        "hora":"16:34",
        "movimiento":"Ingreso recibido",
        "cantidad": 96.68,
        "concepto":"Cuota mensual",
        "usuario_asociado": "Covirán",
        "saldo":383.65,
        "cuenta":"Cuenta 1",
        "categoria":"Alimentación"
    },
    {
        "fecha":"2025-01-12",
        "año":"2025",
        "mes":"01",
        "hora":"17:54",
        "movimiento":"Ingreso recibido",
        "cantidad": 73.26,
        "concepto":"Cuota mensual",
        "usuario_asociado": "Bodega El Vino Bueno",
        "saldo":459.53,
        "cuenta":"Cuenta 2",
        "categoria":"Servicios y comercio general"
    },
    {
        "fecha":"2025-01-12",
        "año":"2025",
        "mes":"01",
        "hora":"00:36",
        "movimiento":"Ingreso recibido",
        "cantidad": 69.18,
        "concepto":"Donación",
        "usuario_asociado": "Bodega El Vino Bueno",
        "saldo":494.27,
        "cuenta":"Cuenta 2",
        "categoria":"Arte y cultura"
    },
    {
        "fecha":"2025-01-25",
        "año":"2025",
        "mes":"01",
        "hora":"09:30",
        "movimiento":"Transferencia enviada",
        "cantidad": -68.99,
        "concepto":"Pago de servicio",
        "usuario_asociado": "Covirán",
        "saldo":265.74,
        "cuenta":"Cuenta 2",
        "categoria":"Deporte y ocio"
    },
    {
        "fecha":"2025-01-25",
        "año":"2025",
        "mes":"01",
        "hora":"22:16",
        "movimiento":"Pago a usuario",
        "cantidad": 51.41,
        "concepto":"Compra en tienda",
        "usuario_asociado": "Tripontzi Jatetxea",
        "saldo":294.29,
        "cuenta":"Cuenta 2",
        "categoria":"Alimentación"
    },
    {
        "fecha":"2025-01-25",
        "año":"2025",
        "mes":"01",
        "hora":"06:04",
        "movimiento":"Pago a usuario",
        "cantidad": 79.53,
        "concepto":"Compra en tienda",
        "usuario_asociado": "Bar El Rincón",
        "saldo":474.71,
        "cuenta":"Cuenta 2",
        "categoria":"Servicios y comercio general"
    },
    {
        "fecha":"2025-01-21",
        "año":"2025",
        "mes":"01",
        "hora":"16:44",
        "movimiento":"Transferencia enviada",
        "cantidad":- 42.1,
        "concepto":"Pago de servicio",
        "usuario_asociado": "Carnicería Jose Luis",
        "saldo":394.73,
        "cuenta":"Cuenta 2",
        "categoria":"Industria y construcción"
    },
    {
        "fecha":"2025-01-21",
        "año":"2025",
        "mes":"01",
        "hora":"23:53",
        "movimiento":"Pago a usuario",
        "cantidad": 46.43,
        "concepto":"Donación",
        "usuario_asociado": "Supermercado Díaz",
        "saldo":328.53,
        "cuenta":"Ekhi Hernani",
        "categoria":"Hostelería"
    },
    {
        "fecha":"2025-01-13",
        "año":"2025",
        "mes":"01",
        "hora":"20:54",
        "movimiento":"Transferencia enviada",
        "cantidad":- 33.4,
        "concepto":"Compra en tienda",
        "usuario_asociado": "Frutería La Huerta",
        "saldo":261.87,
        "cuenta":"Ekhi Hernani",
        "categoria":"Servicios y comercio general"
    },
    {
        "fecha":"2025-01-13",
        "año":"2025",
        "mes":"01",
        "hora":"23:23",
        "movimiento":"Ingreso recibido",
        "cantidad": 72.32,
        "concepto":"Pago de servicio",
        "usuario_asociado": "Supermercado Díaz",
        "saldo":381.03,
        "cuenta":"Ekhi Hernani",
        "categoria":"Moda y complementos"
    },
    {
        "fecha":"2025-01-13",
        "año":"2025",
        "mes":"01",
        "hora":"13:22",
        "movimiento":"Pago a usuario",
        "cantidad": 82.63,
        "concepto":"Compra en tienda",
        "usuario_asociado": "Panadería OA",
        "saldo":54.92,
        "cuenta":"Cuenta 1",
        "categoria":"Industria y construcción"
    },
    {
        "fecha":"2024-01-20",
        "año":"2024",
        "mes":"01",
        "hora":"07:38",
        "movimiento":"Pago a usuario",
        "cantidad": 37.67,
        "concepto":"Cuota mensual",
        "usuario_asociado": "Carnicería Jose Luis",
        "saldo":247.22,
        "cuenta":"Cuenta 2",
        "categoria":"Servicios y comercio general"
    },
    {
        "fecha":"2024-01-02",
        "año":"2024",
        "mes":"01",
        "hora":"08:09",
        "movimiento":"Pago a usuario",
        "cantidad": 97.66,
        "concepto":"Cuota mensual",
        "usuario_asociado": "Bar El Rincón",
        "saldo":466.24,
        "cuenta":"Ekhi Hernani",
        "categoria":"Hostelería"
    },
    {
        "fecha":"2024-01-02",
        "año":"2024",
        "mes":"01",
        "hora":"15:12",
        "movimiento":"Pago a usuario",
        "cantidad": 61.02,
        "concepto":"Cuota mensual",
        "usuario_asociado": "Bodega El Vino Bueno",
        "saldo":146.88,
        "cuenta":"Ekhi Hernani",
        "categoria":"Industria y construcción"
    },
    {
        "fecha":"2024-01-02",
        "año":"2024",
        "mes":"01",
        "hora":"10:37",
        "movimiento":"Ingreso recibido",
        "cantidad": 44.17,
        "concepto":"Compra en tienda",
        "usuario_asociado": "Tienda EcoVida",
        "saldo":377.87,
        "cuenta":"Ekhi Hernani",
        "categoria":"Moda y complementos"
    },
    {
        "fecha":"2024-01-05",
        "año":"2024",
        "mes":"01",
        "hora":"21:13",
        "movimiento":"Transferencia enviada",
        "cantidad": -54.18,
        "concepto":"Donación",
        "usuario_asociado": "Tripontzi Jatetxea",
        "saldo":52.37,
        "cuenta":"Ekhi Hernani",
        "categoria":"Industria y construcción"
    },
    {
        "fecha":"2024-01-05",
        "año":"2024",
        "mes":"01",
        "hora":"22:53",
        "movimiento":"Transferencia enviada",
        "cantidad": -93.17,
        "concepto":"Compra en tienda",
        "usuario_asociado": "Panadería OA",
        "saldo":152.97,
        "cuenta":"Cuenta 1",
        "categoria":"Arte y cultura"
    },
    {
        "fecha":"2024-01-05",
        "año":"2024",
        "mes":"01",
        "hora":"17:55",
        "movimiento":"Transferencia enviada",
        "cantidad": -85.28,
        "concepto":"Compra en tienda",
        "usuario_asociado": "Supermercado Díaz",
        "saldo":322.4,
        "cuenta":"Cuenta 1",
        "categoria":"Industria y construcción"
    },
    {
        "fecha":"2024-01-05",
        "año":"2024",
        "mes":"01",
        "hora":"01:29",
        "movimiento":"Transferencia enviada",
        "cantidad": -60.72,
        "concepto":"Pago de servicio",
        "usuario_asociado": "Bodega El Vino Bueno",
        "saldo":243.54,
        "cuenta":"Cuenta 3",
        "categoria":"Salud y estética"
    },
    {
        "fecha":"2024-01-10",
        "año":"2024",
        "mes":"01",
        "hora":"22:01",
        "movimiento":"Transferencia enviada",
        "cantidad": -31.81,
        "concepto":"Donación",
        "usuario_asociado": "Panadería OA",
        "saldo":393.47,
        "cuenta":"Cuenta 1",
        "categoria":"Salud y estética"
    },
    {
        "fecha":"2024-01-10",
        "año":"2024",
        "mes":"01",
        "hora":"13:17",
        "movimiento":"Pago a usuario",
        "cantidad": 45.05,
        "concepto":"Compra en tienda",
        "usuario_asociado": "Covirán",
        "saldo":202.73,
        "cuenta":"Ekhi Hernani",
        "categoria":"Alimentación"
    },
    {
        "fecha":"2024-01-10",
        "año":"2024",
        "mes":"01",
        "hora":"16:07",
        "movimiento":"Pago a usuario",
        "cantidad": 44.39,
        "concepto":"Donación",
        "usuario_asociado": "Tripontzi Jatetxea",
        "saldo":364.8,
        "cuenta":"Cuenta 2",
        "categoria":"Alimentación"
    },
    {
        "fecha":"2024-01-10",
        "año":"2024",
        "mes":"01",
        "hora":"11:46",
        "movimiento":"Ingreso recibido",
        "cantidad": 44.88,
        "concepto":"Cuota mensual",
        "usuario_asociado": "Carnicería Jose Luis",
        "saldo":411.23,
        "cuenta":"Cuenta 1",
        "categoria":"Hostelería"
    },
    {
        "fecha":"2024-01-26",
        "año":"2024",
        "mes":"01",
        "hora":"19:49",
        "movimiento":"Ingreso recibido",
        "cantidad": 19.11,
        "concepto":"Compra en tienda",
        "usuario_asociado": "Panadería OA",
        "saldo":306.21,
        "cuenta":"Cuenta 2",
        "categoria":"Deporte y ocio"
    },
    {
        "fecha":"2024-01-26",
        "año":"2024",
        "mes":"01",
        "hora":"06:45",
        "movimiento":"Transferencia enviada",
        "cantidad":- 18.4,
        "concepto":"Donación",
        "usuario_asociado": "Frutería La Huerta",
        "saldo":254.84,
        "cuenta":"Cuenta 3",
        "categoria":"Asociaciones y cooperativas"
    },
    {
        "fecha":"2024-01-23",
        "año":"2024",
        "mes":"01",
        "hora":"09:16",
        "movimiento":"Transferencia enviada",
        "cantidad": -75.97,
        "concepto":"Cuota mensual",
        "usuario_asociado": "Panadería OA",
        "saldo":238.26,
        "cuenta":"Cuenta 1",
        "categoria":"Asociaciones y cooperativas"
    },
    {
        "fecha":"2024-01-21",
        "año":"2024",
        "mes":"01",
        "hora":"20:28",
        "movimiento":"Transferencia enviada",
        "cantidad": -79.45,
        "concepto":"Compra en tienda",
        "usuario_asociado": "Tripontzi Jatetxea",
        "saldo":88.66,
        "cuenta":"Ekhi Hernani",
        "categoria":"Industria y construcción"
    },
    {
        "fecha":"2024-01-19",
        "año":"2024",
        "mes":"01",
        "hora":"23:10",
        "movimiento":"Transferencia enviada",
        "cantidad": -75.81,
        "concepto":"Donación",
        "usuario_asociado": "Carnicería Jose Luis",
        "saldo":481.49,
        "cuenta":"Cuenta 3",
        "categoria":"Arte y cultura"
    },
    {
        "fecha":"2024-01-29",
        "año":"2024",
        "mes":"01",
        "hora":"00:08",
        "movimiento":"Ingreso recibido",
        "cantidad": 62.24,
        "concepto":"Donación",
        "usuario_asociado": "Bodega El Vino Bueno",
        "saldo":98.82,
        "cuenta":"Cuenta 2",
        "categoria":"Industria y construcción"
    },
    {
        "fecha":"2024-01-30",
        "año":"2024",
        "mes":"01",
        "hora":"18:36",
        "movimiento":"Pago a usuario",
        "cantidad": 71.11,
        "concepto":"Cuota mensual",
        "usuario_asociado": "Bar El Rincón",
        "saldo":249.04,
        "cuenta":"Cuenta 2",
        "categoria":"Servicios y comercio general"
    },
    {
        "fecha":"2024-01-30",
        "año":"2024",
        "mes":"01",
        "hora":"02:30",
        "movimiento":"Pago a usuario",
        "cantidad": 19.14,
        "concepto":"Pago de servicio",
        "usuario_asociado": "Tienda EcoVida",
        "saldo":121.17,
        "cuenta":"Ekhi Hernani",
        "categoria":"Deporte y ocio"
    }
];

export default mockData;